{% set name = "dynasor" %}
{% set version = "1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 511f0913508b4a256b0bcf882337305341dcde894aa17b79ccb9502b6e9289eb
  patches:
    - config.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win or py2k]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - pip
    - numpy
    - ase
    - importlib-metadata <5
    - numba

test:
  imports:
    - dsf
  commands:
    - pip check

about:
  home: https://dynasor.materialsmodeling.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A tool for calculating dynamical structure factors

  description: |
    dynasor is a simple tool for calculating total and partial 
    dynamical structure factors as well as current correlation 
    functions from molecular dynamics (MD) simulations. The main 
    input consists of a trajectory output from a MD simulation, 
    i.e., a file containing snapshots of the particle coordinates 
    and optionally velocities that correspond to consecutive, 
    equally spaced points in (simulation) time.
  doc_url: https://dynasor.materialsmodeling.org
  dev_url: https://gitlab.com/materials-modeling/dynasor

extra:
  recipe-maintainers:
    - jan-janssen
    - erhart1
