travis:
  secure:
    BINSTAR_TOKEN: F7vAnAuZQAEbvogJmVUSJCKg5mzzIyF5xFo/WGLuSyMpDC82vvPM05qbdgR7xnnUCySnkxHT1RiYAtvHkOMVds8fub1ojKHr2fjMLkDNjkz8HMb+bXawvcbh1IhvbaMmpqopyDJMmljpt80xfpHlP9lBP7p2l+p+lIEG1HPMS7lV9Tm/qrt11rIW/GMgdB1p+yI/H39qRpJZzJqhu2VjEkv8XtjNXxOCtlRBk0ad5sWXtg6igO/eM1tyT10FXv3f0JneCpvvEmfq6QU/4D8nbpYWTuU5nuGarBb3mnqpK3Y3jm32kj3GBqRSCV/+RQT4NEonTPfnhVCJfr3URjUleVk4IRyB1xcwv5xxvwhfEahuzjnT/OL1fbyxefsUbYERpZORvSVFx5RRW6ekv7YJaFdieyOExtkWcEMman8uHlr1EvJM10OyLmOcAVMqXvW+rs+kp2EBYcjlsyr5huqStfxTQYCpk09tdNltc7XvjbBdB70AiJkhlUZOsHwXYL7QvMG/5pVN6xqCn6kMF1D/z6MF5YR4KXbpYV1tQ1PshbeibKYGkrtttD9VZutCRhIWFSINhhchxoEZCiRNYZjXqimkLyaVbV32kc/NyHSuHQlcTHeCEmrdBSnWvMAU+gVZp4ZRU5aDES4YkNQAfRziFXxKrQ455Du/z3lBl9oegKM=
bot:
  automerge: true
conda_forge_output_validation: true
